### ISSUE TITLE
unify module imports. replace all `require` with es imports?

### ISSUE THREAD

**Issue by morlay** [react-dnd/react-dnd#1045]
https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/createSourceFactory.ts#L3
https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd-html5-backend/src/BrowserDetector.ts#L1

There are different module imports.
In Typescript,  this will transform to different codes. `import` way will have one more `__importDefault` wrapper of require.

The questions is .
Sometimes in webpack, we use `lodash-es` instead of `lodash` for `tree-shaking` or other production purpose.

But `lodash-es/memoize` couldn't be imported by `require` directly.

Maybe we need to unify module imports.

Or provide an es version for all sub packages. `module` or `jsnext:main` in `package.json` can be defined like `main` with different dir.

Thanks.

**Comment by darthtrevino** [comment]
So the reasoning here is:
* It's preferable to avoid importing all of lodash, as it's pretty large library
* Typescript doesn't work with `import memoize from 'lodash/memoize'`

Our solution in this case is to just use a require() manually, which bypasses the types typings, but works just fine in webpack.  

I don't mind making an attempt to use `imports` consistently, but I think the right approach here would be to use a lodash microlibrary like `lodash.memoize` instead of a big global import.

**Comment by morlay** [comment]
@darthtrevino 

> It's preferable to avoid importing all of lodash, as it's pretty large library

We could put `module` or `jsnext:main` in `package.json`, and generate another version which keeping es imports, like https://github.com/ReactiveX/rxjs did.
modern frontend packer as webpack and rollup.js will process it by tree-shaking. so it will not increase the final size.

And my package https://github.com/morlay/typescript-plugin-lodash may be helpful.
We could write codes consistently, like`import { memoize } from "lodash"`, and it will be transformed to `import * as memoize from 'lodash/memoize', (we use this plugin before ts tranforming), then final result will be `var memoize = require("lodash/memoize")`.
