### ISSUE TITLE
Module not found: Can't resolve './Constants' in 'D:\desktop\ant_design_pro\onefox\src\components\Drag'

### ISSUE THREAD

**Issue by yaoyuande** [react-dnd/react-dnd#1055]
**Describe the bug**
Module not found: Can't resolve './Constants' in 'D:\desktop\ant_design_pro\onefox\src\components\Drag'
**To Reproduce**
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { DragSource } from 'react-dnd';
import { ItemTypes } from './Constants';

Where is the Constants? How  can I import the ItemTypes ?
**Expected behavior**

**Screenshots**

Browser   chrome

**Additional context**

**Comment by atfzl** [comment]
@yaoyuande seems like this issue is not related to `react-dnd`.

**Comment by amazingmarvin** [comment]
In react-dnd, every drag source has a type.  These are things you define in your program.  So in my app I have types "task" and "project", but you might have "contact" and "organization".  If you don't want to type out these strings all the time (since you might misspell theme), you can store them all in a file:

```javascript
// Constants.js
export default {
  CONTACT: "contact",
  ORGANIZATION: "organization",
}
```

then in your e.g. Drag/Contact.js you would use:

```javascript
import ItemTypes from "./Constants";

class Contact extends Component {
  ...
}

Contact = DragSource(ItemTypes.CONTACT, ...)(Contact)
export { Contact };
```

It looks like your problem is that you didn't define a Constants.js file or it isn't in the Drag directory on your PC!

**Comment by yaoyuande** [comment]
@amazingmarvin Thank you very much!
