### ISSUE TITLE
 endDrag not being called when dropping target into valid target

### ISSUE THREAD

**Issue by emarques** [react-dnd/react-dnd#1080]
**Describe the bug**
According to the [documentation](http://react-dnd.github.io/react-dnd/docs-drag-source.html):

> For every beginDrag call, a corresponding endDrag call is guaranteed.

But using versions 4.0.5 of React DnD and DnD HTML5 backend, the endDrag event is only called when the DragSource is dropped in a place where it can't be dropped, e.g. outside the drop area

**To Reproduce**
```
const eventSource = {
    beginDrag(props) {
        console.log("Starting drag")
    },
    endDrag(props) {
        console.log("Ending drag")
    }
};
```

**Expected behavior**
There should be a print of "Ending drag" after each "Starting drag"

**Screenshots**
![image](https://user-images.githubusercontent.com/2248021/41424841-13c38e3a-6ff7-11e8-9849-3f2644f565b5.png)

**Comment by raub** [comment]
Same here. Updated from 2.x and it stopped working. I apply a style when dragging starts, and I rely on it ending to remove the style. Is there a workaround?

**Comment by raub** [comment]
It has to do with react `ref` being called on drag source component with `null`, which updates the `.component` property of the current `SourceImpl`. That in turn goes into this condition https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/createSourceFactory.ts#L110 and makes an early return, without calling the `endDrag`.

Is this behavior even comply with the doc? I'm pretty fine getting `null` as a component, since I don't even receive that parameter in my callback. But if I pass the callback, please be kind enough to at least call it.
