### ISSUE TITLE
react-dnd v5.0.1 

### ISSUE THREAD

**Issue by tomciopp** [react-dnd/react-dnd#1091]
It looks like v5.0.1 was not published for the react-dnd package but was for the html5-backend. Unless I am mistaken shouldn't these versions always be in lockstep?

**Comment by darthtrevino** [comment]
So with lerna the version always ticks along, but whether or not to publish a package depends on:
   * Did the source code for that package change in git?
   * Is it downstream, topologically of a package that did change in git?

In our case, 5.0.1 was a change to the testBackend, but since no packages depend on it, the version change stops propagation there.
