### ISSUE TITLE
react-dnd version 5.0.0 is failing tests

### ISSUE THREAD

**Issue by ad1992** [react-dnd/react-dnd#1098]
Hi, We have been using the react-dnd library in [react-tags](https://github.com/prakhar1989/react-tags). After upgrading to v5.0.0, the specs start breaking,  giving error `    Enzyme Internal Error: unknown node with tag 13`

This seems to be an [enzyme related error](https://github.com/airbnb/enzyme/issues/1598) but since its happening after upgrading react-dnd  to v5.0.0 so want to make know if there is anything which needs to fixed in the react-dnd library.

Here is the [travis link](https://travis-ci.org/prakhar1989/react-tags/builds/398803168)

Please feel free to close this issue if its not related to `react-dnd`

**Comment by ad1992** [comment]
any updates?

**Comment by darthtrevino** [comment]
I'll have to dig into this to see whether we can resolve it here. Anyone with time to investigate this is welcome to report on any conclusions here

**Comment by rhinoceraptor** [comment]
The issue is enzyme [not supporting the new and improved React context API](https://github.com/airbnb/enzyme/issues/1509).

It seems like they're waiting to release until they fix their context testing features (???), [the fix](https://github.com/airbnb/enzyme/pull/1513) to at least be able to ```mount()``` components that use the new context API has been merged for three months and they haven't released it yet. Very frustrating,

There's a couple suggestions in the thread, in the meantime I will just be using react-dnd@3.0.2 since that seems to be the last version before switching to the new context API.

**Comment by sumthief** [comment]
Hi, I have faced with the same problem.

Please check [this](https://github.com/airbnb/enzyme/issues/1509#issuecomment-398125800). Updating to newer version of enzyme-adapter-react (from 1.1.1 to 1.1.3) solved this problem for me.

**Comment by ad1992** [comment]
This was fixed with enzyme latest release. closing this.
