### ISSUE TITLE
Getting error TS1238 after upgrading to version 6

### ISSUE THREAD

**Issue by HenrikBechmann** [react-dnd/react-dnd#1164]
**Describe the bug**

upgraded to version 6; getting errors like this:

```
databox/resizetab.view.tsx(76,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'DndComponentClass<any>' is not assignable to type 'typeof ResizeTab'.
    Type 'DndComponent<any>' is not assignable to type 'ResizeTab'.
      Types of property 'render' are incompatible.
        Type '() => ReactNode' is not assignable to type '() => Element'.
          Type 'ReactNode' is not assignable to type 'Element'.
            Type 'string' is not assignable to type 'Element'.
```

using decorators like this:

```
@DragSource( DragTypes.RESIZETAB, resizeHandlers, resizeProps )
class ResizeTab extends React.Component<any,any> {

```

using Typescript 3.1.6

I'll revert to dnd version 5 for now.

**Comment by darthtrevino** [comment]
Yes, the reason we did a major change was because of this issue. We had to choose between supporting TS decorators or having correct types for clients. The issue here is that TS decorators have to emit something that's assignable to the input type, and we wanted to remove the collected props from the final props interface.

**Comment by darthtrevino** [comment]
https://github.com/react-dnd/react-dnd/releases/tag/v6.0.0

**Comment by HenrikBechmann** [comment]
Ah, gotcha, thanks. I didn't see the release notes.
