### ISSUE TITLE
Convert examples back to JS

### ISSUE THREAD

**Issue by gaearon** [react-dnd/react-dnd#1208]
Hi folks!

I must have missed some context — why were examples converted to TypeScript? It makes sense if you find development in TS more productive, but most users use JavaScript. I think it's important that we keep examples accessible to the majority of developers.

How do you feel about leaving examples in JS?

**Comment by gaearon** [comment]
Specifically, I mean that clicking "browse source" on pages like http://react-dnd.github.io/react-dnd/examples/dustbin/single-target now leads to a TS implementation. I think that was a mistake.

**Comment by stnwk** [comment]
Please don‘t remove the TS examples. If you have to keep the JS example back, I think that‘s fine and would also be well appreciated. But figuring out how to use such a complex lib in TS without actual code examples is a pain in the ass.

I for one was really, really grateful to have found some TS examples.

**Comment by roth1002** [comment]
Agree both TS and JS example :)

**Comment by augbog** [comment]
I think it's nice to have both examples (but selfishly that's because right now I'm playing with Typescript) but I agree it is really confusing right now. The documentation guide code snippets are all in JS and then the documentation examples are in Typescript. It's not that bad because the syntax is very similar but can be jarring for new users who might be going back and forth for reference.

I recall a while back the documentation had a way to toggle and show how to write with or without Decorators/ES7 syntax. Anyway we can have something like that for JS / Typescript snippets and examples? (willing to contribute if someone can point me to how we handled the toggling of docs before)

**Comment by kylebebak** [comment]
If Dan Abramov can't get a response from a maintainer I think it's safe to say we're shouting into the void.

And yeah, this is extremely confusing. The fact that dnd developers use TypeScript doesn't change the fact that this is a React library, and React is a **JavaScript** library.

JS examples ought to come first, not TS. **JS is valid TS, not the other way around...**

**Comment by djnorrisdev** [comment]
Having examples in TS is incredibly confusing to those of use who have never used it. I'd love to see some JS examples in the docs.

**Comment by knpwrs** [comment]
It should be trivial to set up a build where types are stripped from the examples. This could be done with either Babel or the TypeScript compiler.

**Comment by peterpme** [comment]
:wave:

As much as I admire the effort that's been put into this project, the examples are pretty complex.

This doesn't need to be optimized using all the fancy new features Typescript / our new build systems offer, it just needs to be easy to grok.

I'm looking through the simple sorting example wondering what "as" does and whether that's a new es6 / babel feature or typescript. 

I can't get the examples working because I've never used typescript.

**Comment by jbrawnjr** [comment]
Without the TypeScript examples, it is difficult to understand how the types are supposed to work. Since the site and tutorials are all written in JavaScript, the TS code examples are the ***only*** official guidance for using TS.

**Comment by darthtrevino** [comment]
@gaearon Sorry about getting to this late. The examples are kind of playing double-duty as a set of integration tests at the moment. Having them in TS has been very helpful in verifying correctness of the types we provide.

I'm not opposed to having some Vanilla JS examples, but I would favor using Markdown for those, or having them as a separate thing from the TS examples.

**Comment by darthtrevino** [comment]
Also, one thing we've floated from time to time is using the examples as a suite of automated integration tests as well, which is why they are in a separate package now.

**Comment by peterpme** [comment]
@darthtrevino appreciate you responding and understanding the situation :smile:
