### ISSUE TITLE
Drop target spec's hover function returns null for component parameter in v7.4.3

### ISSUE THREAD

**Issue by svencowart** [react-dnd/react-dnd#1320]
**Describe the bug**
When defining the hover function inside of a drop target specification on a functional component, hover's component parameter returns null.

**To Reproduce**
Bug can be observed here: https://codesandbox.io/embed/2j04wp1y1n

This is the same code as the simple example except that the hover function console.log's the component parameter.  See how the component parameter value is null.

**Expected behavior**
The component parameter should not be null.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Chrome
 - Version: 73.0.3683.86

**Additional context**
I might be wrong, but after reading through various diffs on the v7.4.3 tag, it seems like this might be an issue because react-dnd now requires ref to be present.  This was working prior to v7.4.3, so if that is the case now, would that not be a major breaking change? 
(https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers)

**Comment by RobPethick** [comment]
This is explained in the documentation as the case, you've got to wrap any functional components

http://react-dnd.github.io/react-dnd/docs/api/drop-target


component: When specified, it is the instance of your component. Use it to access the underlying DOM node for position or size measurements, or to call setState, and other component methods. It is purposefully missing from canDrop because the instance may not be available by the time it is called. If you want this method to depend on the component's state, consider lifting the state to the parent component, so that you can just use props. Generally your code will be cleaner if you rely on props instead whenever possible. *Do note this is always null when hovering stateless components.*

**Comment by svencowart** [comment]
I tested the sandbox link I posted with version 7.4.2 and you are right, the component is null.  Interestingly enough, with version 7.4.2 in my own project, I am using only function components without refs and the component property is **not** null.  Potentially relevant information is that the parent components manage state via hooks.  Not sure what to make of this.
