### ISSUE TITLE
Cannot call endDrag while not dragging

### ISSUE THREAD

**Issue by z784324922** [react-dnd/react-dnd#1481]

**Comment by gogoyqj** [comment]
i guess that ur using `uglifyjs-webpack-plugin`...

**Comment by tvedtorama** [comment]
I have the same problem, `invariant violation`.  Turns out it only happens with the **uglify enabled**.

**Comment by ctiller15** [comment]
Recently ran into this exact same issue while trying to copy the tutorial with some minor modifications, (working on a nested component, using `useState` instead of the observer file), and I ran into this error as well.

Also running [the example given on the project website](https://zr7ly.csb.app/) gives me the same error after dragging/dropping the knight.

As far as I can tell I am running the latest version of every package. Is there some other solution for this?

Repo is [here](https://github.com/ctiller15/react-dnd-chess)
