### ISSUE TITLE
when I run project，report errors：Unexpected token export

### ISSUE THREAD

**Issue by sunlanlisa** [react-dnd/react-dnd#1524]
I run this project, then react-dnd module Report errors：
/project/node_modules/react-dnd/dist/esm/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './common';
                                                              ^^^^^^

SyntaxError: Unexpected token export

How can I do?

**Comment by JackWCollins** [comment]
I am also seeing this error. Haven't been able to find a solution yet

**Comment by tom-james-watson** [comment]
I had the same problem - they're directly exporting ES6 on `react-dnd`. Instead, just use the drop-in-replacement `react-dnd-cjs` and it should work fine.

**Comment by JackWCollins** [comment]
Thanks @tom-james-watson that worked perfectly

**Comment by timorss** [comment]
> react-dnd-cjs

Hey
How exactly?

**Comment by JackWCollins** [comment]
@timorss  It's another library. https://www.npmjs.com/package/react-dnd-cjs

just do `npm i react-dnd-cjs` and just use it in place of `react-dnd`, for example: 

`import { DndProvider } from 'react-dnd-cjs';`

**Comment by softwareplumber** [comment]
Gosh. Anyone have any clue when this happened? Given how hard it is to mess with create-react-app's stack, having a react module that won't work out of the box with react seems a bit regressive.

**Comment by darthtrevino** [comment]
What version of react-scripts are you using? There is a test application using create-react-app under `packages/documentation/cra-test`

**Comment by fletcherist** [comment]
oh guys, this was truly unexpected :)

**Comment by mikesarfaty** [comment]
bump, this is breaking. Is anything being done?

**Comment by darthtrevino** [comment]
If your runtime environment doesn't support esm, you should use react-dnd-cjs.

**Comment by mikesarfaty** [comment]
ty

**Comment by softwareplumber** [comment]
So every project that uses react-dnd should fork into two versions, one which includes react-dnd and one which includes react-dnd-cjs?

Me, I use react-sortable-tree which uses react-dnd. When react-sortable-tree updated to a newer react-dnd, this issue broke my vanilla CRA stack. I spend about 2 days trying to resolve it, then gave up. There are a few other folks using react-sortable-tree who have reported the same problem. This may be because of the way react-sortable-tree uses react-dnd, I don’t know. 

In the mystical future date when I’m caught up with all my commitments, I might make the effort to delve into the create-react-app stack deep enough to figure out exactly what is going on.

For now I’m just stuck using the last version of react-dnd prior to this change.

**Comment by darthtrevino** [comment]
The transition to ESM, to be frank, has been a bit of a nightmare all around. There are developers who demand ESM to get proper tree-shaking support to improve their bundle sizes, and there are developers who demand CommonJS for interop with legacy bundler configurations and NodeJS tooling.

My hopes is that with Node 14, we can finally move forward as an ecosystem with ESM, but I guess we'll see. Depending on how the ESM support of Node 14 looks, we may use the conditional exports feature of NodeJS to support dual CJS/ESM packages. This will be a major version change and will probably anger ESM purists.
