### ISSUE TITLE
using 3rd party library

### ISSUE THREAD

**Issue by megarg** [react-dnd/react-dnd#2709]
I am trying to figure out how to use 3rd party library as a drag source and also as drag target. Use case would be using reactstrap "Container" as a target and dropping "Row" or other components inside it to build a page

I reviewed issue#
https://github.com/react-dnd/react-dnd/issues/347

But it did not answer completely. 
Q1. Can you also use 3rd part library as a drag target. 
Q2. Looks like findDOMNode does not work on functional components. How to do have drag/drop with some 3rd party components if they are functional?

**Comment by leftdevel** [comment]
The only requirement for react-dnd to work is to be able to attach a ref to a dom node. Since only primitive react components make use of refs then the library you use must somehow forward it from their rich component to the inner wrapping element. For reactstrap they allow you to pass a innerRef prop.

see https://reactstrap.github.io/components/form/

**Comment by megarg** [comment]
Thanks a lot. This worked.
