### ISSUE TITLE
How to resize a preview based on the real dragged element? 

### ISSUE THREAD

**Issue by Vadorequest** [react-dnd/react-dnd#446]
I have a draggable text, but I want to display that text with a width/height equal to about 20% of its real size. I wonder how I am supposed to resize of apply any styling to the preview screenshot. I don't know how to target the screenshot itself. Is there any way?

**Comment by tarjei** [comment]
Look into the documentation for DragLayer (http://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html)

**Comment by johnkaplantech** [comment]
Hey I have a similar issue - want to give an image for the drag preview and react dnd is making it too big - I tried setting the image size with width/height and style.w/h before passing to connectDragPreview with no effect. Have combed the documentation & couldn't find any mention of resizing the preview image. The actual html element that displays the image in this case is buried deep down in a library component so that's not easily accessible either, so the most straightforward solution would be if connectDragPreview/dragPreview could expose a resizing option (or even better honor the sizing of the image passed in).

**Comment by haimyyy** [comment]
Any update on this issue?

**Comment by ashwanipayal** [comment]
@MrBr , thanks it's working.
