### ISSUE TITLE
dragged <li> disappears while dragging in chrome 50.x

### ISSUE THREAD

**Issue by ceguster** [react-dnd/react-dnd#454]
Reproduced by altering source of NaiveDrag example, as follows: 

```
diff --git a/examples/02 Drag Around/Naive/Box.js b/examples/02 Drag Around/Naive/Box.js
index dd28d7a..9e29550 100644
--- a/examples/02 Drag Around/Naive/Box.js  
+++ b/examples/02 Drag Around/Naive/Box.js  
@@ -39,9 +39,13 @@ export default class Box extends Component {
     }

     return connectDragSource(
-      <div style={{ ...style, left, top }}>
-        {children}
-      </div>
+      <ul>
+        <li style={{ ...style, left, top }}>
+          {children}
+        </li>
+      </ul>
     );
   }
```

As long as position on Box is absolute, relative, or fixed, there is no drag preview of the element.
I think this is a Chrome bug, as it only showed up in 50.x, but there may be a react-dnd workaround. 
Thanks!

**Comment by mattholtom** [comment]
We also have this issue on our project.
`
connectDragSource(
        <li>...</li>
)
`

**Comment by jbfm21** [comment]
In my case, to resolve this problem I add z-index style in LI tag: <li
*style="z-index:10"*>...</li>

**Comment by stevengoldberg** [comment]
Also experiencing this issue. Removing `position: relative` from some of the child elements is a temporary workaround in my case, for the most part. Adding `z-index` didn't make a difference.

**Comment by mtomcal** [comment]
I am experiencing the same problems. I used `position: absolute` as @stevengoldberg did and the previews magically came back. But, it also broke my component layout.

**Comment by mtomcal** [comment]
I just found another potential workaround:

If you promote your draggable component to a layer it brings back the drag preview image. Add this property to your draggable and see if it works: `transform: 'translate3d(0,0,0)'`

**Comment by stevengoldberg** [comment]
Excellent suggestion @mtomcal, that's a solid workaround for me!

**Comment by renarsvilnis** [comment]
I'd like share experience having & solving incorrect drag preview, which might be useful for someone searching issues.

I had created a `Sortable` react component that handles the sorting of passed in elements. In some cases `Sortable` didn't render correct preview - instead of the dragged block it preview all of the page.
I added `position: relative` to the draggable elements that are wrapped in `connectDragPreview` and that solved my problem, which is the opposite what @stevengoldberg has suggesting. But I'm ussing `connectDragPreview` on a `<div>` instead of a `<li>` element, if that matters.

**Comment by austinknight** [comment]
I have a component that contains the all of the draggable element functionality that just wraps whatever items you want to be draggable. Initially the preview wasn't showing when dragging. I added a higher z-index to the div that wraps the children and that fixed the problem for me. Also using a div.

inside my render function I set the draggable-item-wrap class with the higher z-index:
```
return connectDragSource(connectDropTarget(<div className="draggable-item-wrap">{this.props.children}</div>))
```

Anything wrapped in my draggable item component can be dragged:
```
<DraggableItem onMove={...} someOtherProp{...}>
</DraggableItem
```

**Comment by kesne** [comment]
It seems like we have some good workarounds to the problem of bad previews. I've seen this come up before, and it has even come up in the project that I've been working on as well.

I wonder if we can come up with an elegant solution to the problem. I feel as though this is partially due to the HTML5 backend.

**Comment by stevengoldberg** [comment]
@kesne I think we've established that it's a Chrome bug. It didn't occur before Chrome 50, and doesn't happen in Firefox. We've given up trying to fix it in our app.

**Comment by ouchxp** [comment]
`z-index:1` works for us

**Comment by joaoreynolds** [comment]
I cannot recommend @mtomcal  's recommendation enough. I didn't necessarily need the `translate3d(0,0,0)`, what I really needed was to just bypass the html5 preview and create my own `DragLayer`. It took a lot of refactoring and gnashing of teeth, but overall functionality is way better anyway now. Here's a great example of using DragLayer: https://github.com/react-dnd/react-dnd/tree/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer

**Comment by DieLaughing** [comment]
I wish I could see your great example.
