### ISSUE TITLE
Drag preview is very dim, how to style it darker?

### ISSUE THREAD

**Issue by jeghers** [react-dnd/react-dnd#494]
When using connectDragPreview inside the render function (so the entire rendered element shows as the preview), it is previewed very dim and faded, hard to see very well.

If I use the componentDidMount technique (calling connectDragPreview earlier to pass in a custom preview of the same element with altered styling), then the preview does not show at all.

If there was simply a runtime value, maybe passed into the props, to tell that it is a preview being rendered, then I could adjust the style accordingly (e.g. to darken the preview to be more visible).

Am I doing something wrong?  Or does the componentDidMount technique only work for images?

**Comment by UsulPro** [comment]
Perhaps you mean that the browser fade big preview by default (with small ones such problems don't occur)
Maybe you can use DragLayer and render anything just as you need - generally it solves all these problems.
But I also join this question, because using DragLayer has the following cons:
- loss in performance (even with good optimization noticeable delay after mouse movement)
- difficult to combine with the DropTarget because it overlaps target element
- harder to realize when you need DragLayer just for preview

I hope to eventually find a way to remove this fade :smile:
