### ISSUE TITLE
Reading keyboard ctrlKey (Alt, Shift) state from monitor

### ISSUE THREAD

**Issue by OlegZee** [react-dnd/react-dnd#512]
I would like to modify drop action behavior depending on ctrl button state.
E.g. if Ctrl is pressed currently dragged item has to be copied to a new place or if Alt is pressed I want to snap dragged item to a grid.
I could obtain button state from DOM events but React DND hides such a detail completely. Opening respective methods via monitor methods would be one of the options to fulfill my request.

**Comment by kesne** [comment]
I don't think this is currently possible. Right now you'd have to maintain that state in the component with document key listeners likely. 

I think the major issue with this is that key events and drag events are pretty separate, so I don't see a clean way of having react-dnd provide key information alongside drag information.

**Comment by OlegZee** [comment]
According to my sources, drag events contain all required stuff:
https://developer.mozilla.org/en-US/docs/Web/Events/dragend. I'm going to
make PR next week
Сб, 20 авг. 2016 г. в 13:12, Jordan Gensler <notifications@github.com>:

**Comment by kesne** [comment]
Oh rad, I stand corrected! That'd be interesting to see implemented!

**Comment by richardolsson** [comment]
Was there ever a PR submitted for this? I solved this in our fork of react-dnd but it broke with recent changes to the library.

We solved it by adding a `meta` property that back-ends could use to send arbitrary data, and used that object in the HTML5 back-end to store the event key information.

**Comment by OlegZee** [comment]
@richardolsson That's a great news! I must confess I've made no progress on this case yet. React-dnd is so multi-layered so I need a pen and piece of paper to design the changes. Taking unit tests and docs into account makes such PR way too complicated for me (at least not a one evening task).
Besides that I'd like to see it a first-class citizen, while `meta` looks like a w.

**Comment by richardolsson** [comment]
At the time, all I did was these two commits (to react-dnd and dnd-core respectively):

https://github.com/zetkin/react-dnd/commit/aedf6d6f39f15e3b8e19311255f71fef4bc218f5
https://github.com/zetkin/dnd-core/commit/dc8dee33455867fe1dc2f4f75f58196f77691732

This broke later when the react-dnd HTML5 backend was split out into a separate library. I'm sure it could be added back in, but it would likely require changes to all three libraries, so it would be three parallel pull requests.

The problem with adding a feature like this as a "first class citizen" is that react-dnd is all about drag and drop, and not all devices where drag and drop might be relevant have a keyboard.

This is why I added it as a "meta" object. It was a way for the back-end to send meta-data that is specific for that back-end, rather than universal to any drag and drop operation.

**Comment by cdauth** [comment]
What I could find about this:
* [An older discussion](https://github.com/react-dnd/react-dnd-html5-backend/issues/23) where someone suggested to handle the bubbling drag events on a parent component and cause it to rerender the dragging child component with props according to the pressed modifier keys
* [This pull request](https://github.com/react-dnd/react-dnd/pull/675) where hard-coded Apple behaviour was added to the code, allowing to switch to Copy mode using the Alt key.

On Windows and Linux, it seems that Ctrl+Drag stands for copy, Shift+Drag for move and Alt+Drag for link. On Apple, it seems that Alt+Drag stands for copy and god knows what other modifier keys there are and what they stand for. There seem to be other platform-specific restrictions, for example on Linux you cannot Alt+Drag at all (because it moves the current window) and on Firefox on Apple you cannot Shift+Drag for some reason.

In our case, we need to distinguish only between two actions, link and copy, so we decided to make a drag without any keys do the link action and a drag with any modifier key a copy action. This way we circumvent the platform differences and people can just use whatever modifier key works on their platform.

We implemented this by hacking the existing Alt key functionality:

```javascript
function isModifierKeyPressed(event) {
    return event.altKey || event.ctrlKey || event.metaKey || event.shiftKey;
}

export const HTML5BackendWithModifierKeys = (manager, context) => {
    const result = HTML5Backend(manager, context);

    result.handleTopDragEnter_ = result.handleTopDragEnter;
    result.handleTopDragEnter = (e) => {
        result.handleTopDragEnter_(e);
        result.altKeyPressed = isModifierKeyPressed(e);
    };

    result.handleTopDragOver_ = result.handleTopDragOver;
    result.handleTopDragOver = (e) => {
        result.handleTopDragOver_(e);
        result.altKeyPressed = isModifierKeyPressed(e);
    };

    return result;
};
```

The key can be pressed either before starting the drag operation or during it. There is one oddity however, that is that pressing or releasing the key is only registered when moving the mouse afterwards. When pressing or releasing the key and then immediately releasing the mouse without moving it, the key press/release is not registered. This seems to be a browser limitation though.

What's really annoying about this workaround still is that react-dnd only allows us to access the dropEffect in the drag end handler (using `monitor.getDropResult()`), but not during the drag operation. This makes it impossible to show which mode is active in the drag preview. I suppose the suggestion of reacting to the bubbling drag events might be a better solution here, but I haven't tried that yet.

**Comment by d07RiV** [comment]
@cdauth the fix doesn't work (anymore?) because getCurrentDropEffect is called *inside* the original handleTopDragX. I'm trying to patch around it without forking the repo, shame that the issue still hasn't been addressed.

I don't suppose you had any luck with bubbling the drop effect?

**Comment by cdauth** [comment]
I'm not sure, when I wrote the hack we were using version 11.1.3, and from the source code it doesn't look like a lot has changed in that method since then. I guess if it doesn't work for you you could also try to modify the event object itself (haven’t tried that code, that’s just how I imagine it):
```javascript
const altKeyHack = (event) => Object.assign(event, { altKey: event.altKey || event.ctrlKey || event.metaKey || event.shiftKey });

export const HTML5BackendWithModifierKeys = (manager, context) => Object.assign(HTML5Backend(manager, context), {
    handleTopDragEnter(e) {
        HTML5Backend.prototype.handleTopDragEnter.call(this, altKeyHack(e));
    }

    handleTopDragOver(e) {
        HTML5Backend.prototype.handleTopDragOver.call(this, altKeyHack(e));
    }
});
```
