### ISSUE TITLE
Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by gabrielenosso** [react-dnd/react-dnd#521]
I am getting this warning...

warning.js:36 Warning: Stateless function components cannot be given refs (See ref "child" in App created by DragDropContext(App)). Attempts to access this ref will fail.

Can anyone help?

I know how to write <App /> as a normal component (extension of React.Component), but I would like to have it as a stateless function
(I'm using ESLint with air-bnb configuration, and it gives me a warning if I use a component as an extension of React.Component without any other property).

Anyway, as this.refs seems to be deprecated in new version of React, maybe there is something in the code that could be changed.

**Comment by dhovart** [comment]
I'm having exactly the same issue. You can reproduce it here: https://github.com/dhovart/solitaire.
This happens with two component only, being decorated respectively by DragDropContext and DragLayer.

It looks to me that they use a ref to store the decorated component instead of using `decorateHandler`.  Any special reason for this?

Thanks a lot for react-dnd, I really like its API.

**Comment by NameFILIP** [comment]
I have the same issue. Made a PR with a fix

**Comment by NameFILIP** [comment]
@gaearon, is there a chance of getting the fix merged?

**Comment by gabrielenosso** [comment]
no updates on that one?

**Comment by gaearon** [comment]
I'm not actively maintaining this library. If you'd like to help merging PRs let me know!

**Comment by NameFILIP** [comment]
Updated the PR
