### ISSUE TITLE
Firefox Bug

### ISSUE THREAD

**Issue by sevikon** [react-dnd/react-dnd#690]
Hi guys, 
it seems to be problem with [simple sortable](react-dnd.github.io/react-dnd/examples-sortable-stress.html) and [chess](http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html) in firefox (version 51.0.1 (64-bit), linux mint). 
In sortable demo dragging stops working after few movements. In chess demo I can't drop knight.
On Chrome and Opera everything works as expected. Also Firefox on Windows works properly. 
Is it possible to fix it?
Best regards,
Konrad

**Comment by courtney7** [comment]
I have the same issue in which the dragging stops working after a few movements. The issue is present in the same demos as @sevikon mentions, and in my own application. With Firefox 50.1.0 on CentOS 7.3, the dragging stops working after a few movements. With Firefox 52.0.1 on CentOS 7.3, it works but is not smooth. Chrome on CentOS 7.3 and IE11 on Windows Server 2008 are both smooth.

Regards,
Courtney

**Comment by carlesba** [comment]
Same problem here. I checked the chess example with Firefox and works randomly.

I have a similar issue in my app sometimes when it runs in firefox, I can't drag/drop elements. When I start dragging some element:
1. **canDrag** is executed
2. **beginDrag** is executed
3. **canDrop** is executed for each droppable element 3 times each!! So if we have 3 droppable areas canDrop is called 9 times.
4. Then **endDrag** is called before I drop the element.

About the step 3, in Chrome **canDrop** is called continuously until you drop. I might guess Firefox is blocking the execution of canDrop so the app becomes buggy.

Any ideas?

**Comment by deanmaster** [comment]
I have problem with 'Cannot call beginDrag while dragging' only on Firefox. even I tried to implement again isDragging but it seems doesn't help. Firefox 52.6.0 ESR only
