### ISSUE TITLE
Add support for CTRL key as a copy modifier

### ISSUE THREAD

**Issue by alexmorleyfinch** [react-dnd/react-dnd#721]
On Windows, the CTRL key is used to signify a 'copy' rather than a 'move' operation, although on a Mac it is ALT.

We needed to offer our clients a way of using either alt or ctrl, as a principle of least surprise.

Here is a pull request which offers a simple solution https://github.com/react-dnd/react-dnd/pull/720

**Comment by th3fallen** [comment]
we found a pretty simple solution to do it without waiting for an upstream change. thought i'd share.

```
import HTML5Backend from 'react-dnd-html5-backend/lib/HTML5Backend';

class HTML5Modifiers extends HTML5Backend {
  handleTopDragEnter(e) {
    super.handleTopDragEnter(e);
    this.altKeyPressed = e.ctrlKey || e.metaKey;
  }
  handleTopDragOver(e) {
    super.handleTopDragOver(e);
    this.altKeyPressed = e.ctrlKey || e.metaKey;
  }
}

export default function createHTML5Backend(manager) {
  return new HTML5Modifiers(manager);
}```

then use that as your backend ezpz

**Comment by dolfelt** [comment]
@alexmorleyfinch That solution looks good, but ideally it would allow for a custom function to specify which keys or conditions should enforce copy. Since we have a lot of Mac customers, we wanted to also support the `metaKey` (aka Command).

And while this solution works and is fairly simple, since we're hacking into private api, it might break in the future.
