### ISSUE TITLE
Custom DragLayer in IE 11 - dragging results in constant toggling between copy and pointer cursors

### ISSUE THREAD

**Issue by dizard2001** [react-dnd/react-dnd#737]
I implemented a custom drag layer for a Kan Ban board using the example:
http://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html

In IE11 I have noticed that the cursor constantly toggles between the copy and pointer cursor when dragging an object. This occurs in the demo example as well. I was just curious if this is a known issue, as I looked through the existing issues to see if anyone else had noticed this before and couldn't find any references.

**Comment by mpseidel** [comment]
Seeing the same in Edge

**Comment by theTechie** [comment]
@dizard2001 - I have experienced similar problems with IE; we chose to fallback and not have any custom drag previews for IE.

**Comment by piotrpawlik** [comment]
Any update on the topic? Still having this issue in IE.

**Comment by jamiewinder** [comment]
One of the symptoms I've found associated with this is that `monitor.isOver()` immediately toggles from `true` to `false` which I think is due to the custom drag layer rendering (if I remove the layer, it stays true as long as you're over the same component). This perhaps suggests it is an issue of react-dnd, unless IE is making it impossible to track for some reason?
