### ISSUE TITLE
Expected to find a valid target.

### ISSUE THREAD

**Issue by qiujunbiao** [react-dnd/react-dnd#764]
![image](https://cloud.githubusercontent.com/assets/3970608/25798606/629f4e24-3414-11e7-95c5-260a7d548fcb.png)

I would like to ask how to solve this problem, is accidental, in the two level of drag and drop will occur

**Comment by mwielocha** [comment]
@cmoad how exactly did you solve the problem? I can't find a workaround and I also can't make react to not unmount the component...?

**Comment by cmoad** [comment]
@mwielocha The code before what I pasted was dynamically setting the drag type id (`DRAGGABLE_CATEGORY_NAV_ITEM`) instead of using a constant. That was causing the remount in our case. The cause of the remount came from the parent, so there wouldn't be a generalized solution. It very much would depend on your parent component.
