### ISSUE TITLE
Button elements do not initiate drag on the parent drag source

### ISSUE THREAD

**Issue by daweffe** [react-dnd/react-dnd#803]
In Firefox, IE, and Edge, <button> elements seem to be blocking the drag start event.  This does not happen in Chrome.  We have complex drag sources with buttons and other elements as children, and this bug is detrimental to the drag and drop experience.

**Comment by blaynem** [comment]
Just ran into this exact same issue. I quickly found an error where it was not working on <a> elements, so figured it would be the same issue with a <button> element. Thankfully on our end, it was very easy to simply replace the <button> elements with a normal <div>.

**Comment by erohin** [comment]
@daweffe https://bugzilla.mozilla.org/show_bug.cgi?id=568313

**Comment by bolyesz** [comment]
The current state seems to be that its working in Firefox but not in IE or Edge. Run into this issue on the current latest version which is v10.0.2.

**Comment by paperbackdragon** [comment]
I'm hitting this problem in Spartan Edge (pre-chromium Edge) specifically. It seems to work in Anaheim (chromium Edge). I specifically need to support Spartan Edge in the app I'm working on, and it's not accurate for us to be using `a` tags or `div`s since it has an `onClick` handler that will send it to a new page, not a static href value. But we may explore using something like `<div role="button">` to get around this. 😞
