### ISSUE TITLE
[Feature request] Custom preview with canDrop from drop target

### ISSUE THREAD

**Issue by scottcheng** [react-dnd/react-dnd#940]
I'm rendering custom drag preview through `DragLayer`, and I found it very hard to customize the preview based on information from the drop target, e.g. whether user can drop at a particular position. I think this is a rather common use case, therefore I propose adding it to the framework.

Concretely, one idea to support this is to expose `canDrop` that drop target spec defines in `DragLayerMonitor`, so drag layer can render the preview differently based on this information.

**Comment by the-owl** [comment]
I'd like to have this feature too. Currently I have to modify a mobx store in `hover` of `DropTarget` to implement a dynamic preview in `DragLayer`.

Maybe it will be better to expose current target rather than `canDrop`, if it's possible? This will make possible different previews for different targets.

**Comment by lostfictions** [comment]
For folks who landed here trying to figure out a solution, there's a workaround in this issue: https://github.com/react-dnd/react-dnd/issues/448

Note that the typings (and documentation!) appear to be missing `getTargetIds()` on DragLayerMonitor, but it's there!
