### ISSUE TITLE
react dnd doesn't work with styled

### ISSUE THREAD

**Issue by unutoiul** [react-dnd/react-dnd#966]
Error: Only native element nodes can now be passed to React DnD connectors.You can either wrap styled.div into a `<div>`, or turn it into a drag source or a drop target itself.

**Comment by slipsnip** [comment]
I can confirm that I also have this same issue.  In my use case wrapping my styled component in div does not work because I am using css grid for layout and it does not support children.  Currently looking for a resolution to this Error.

**Comment by slipsnip** [comment]
I fixed this problem today in my own drag and drop application that uses styled-components.  Best way for me to illustrate the fix is to point you to my repo https://github.com/slipsnip/react-dnd-experiment

The fix:
https://github.com/slipsnip/react-dnd-experiment/commit/be1f4090764deea37a1cf2187d293d2603582b00

New to github, not sure of a better way to show how I solved the problem.
