### ISSUE TITLE
Overlapping Drop Targets

### ISSUE THREAD

**Issue by lbrouckman** [react-dnd/react-dnd#968]
I have two types of drop targets, with different drop handlers. They are arranged sequentially like:
```
<DropTarget Type1>
<DropTarget Type2>
<DropTarget Type1>
<DropTarget Type2>
```
They overlap slightly, and when a drag item isOver a DropTarget (either type) I apply a border to that target. When I am hovering over an area that has both drop targets on it, this causes a flickering behavior as Type1 and Type2 isOver values rapidly change between true and false, affecting the border.
What I want is for Type2 to always take precedence. So if the item is hovering over Type1 and Type2, only Type2 will render it's isOver style. Is there a way to do this?

**Comment by BananaBobby** [comment]
I've got similar issue. I have nested drop targets of the same type. So whenever I hover the child drop target - both (child and parent) hover handlers trigger. However they are triggered one by one and it seems to be a bit hard to ignore the parent one.

I failed to find the solution provided by the library, so currently I'm thinking of adding some timeout, to wait all the handlers trigger and then choose the right one based on their parent ids. Seems to be really fragile solution though.

**Comment by frazboyz** [comment]
I reproduced this issue in the React DND examples page. All you need is one drop target to be bigger than the others.

https://cl.ly/e4a657e34986

**Comment by pathikdevani** [comment]
Any solution on this?

**Comment by topolanekmartin** [comment]
I found possible a solution. Surrounding items are moving since your cursor detects the bottom/top border of the surrounded item while dragging. 

For example - when you drag an item from bottom to top and your cursor reaches the bottom border of the upper item, the upper item would move to the bottom and create space for the dragged item. This is bad. I think this should be done after your cursor reaches the top border of the upper item.

This video explains what I described above https://pqina.nl/media/filepond-drag.mp4. I found this solution while reading an article about animations here https://pqina.nl/blog/animating-width-and-height-without-the-squish-effect/.
