### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by dlgski** [react-dnd/react-dnd#971]
I am receiving this error when I try to use a component within my Drag Target.   My code is pretty simple where I have a common div on the outside of my component, which renders properly.
```

<div>
     <BorderedContainer ... >
          <span>Text here</span>
     </BorderedContainer>
</div>

```

The outer divs are because that is what is required when I created my DropTarget.    The BorderedContainer is a simple React component that takes in different props which will do simple things like highlight, select etc. for visual purposes.  Then there is the text.  This text needs to be able to move in and out of my target.  It moves in fine, but it cannot move out without getting the error:

`Uncaught TypeError: Cannot read property 'nodeName' of undefined`

I dug into this error and found that for some reason sourceNodes has changed.  The pattern I found, was when I initially load a the page with 3 choices, my sourceNodes has 3 values: S08, S10, S12.  Then I drag one choice to a Target, and these source nodes change to S08, S12, S47.  This is still good.  But when I go to drag that choice back, it is looking for S52 for some reason, which does not exist in my sourceNodes.   And that seems to constantly change every time I try to drag the choice out of the dropZone.

To fix this, I took out my custom component and re-wrote it all into my dropZone using divs. 

Can you explain to me why I had to do this?  What is causing the sourceNodes to change all the time when I use this component?  I would just like a better understanding of this limitation.

Thank you!

**Comment by zmayor** [comment]
I met the same problem. Hope someone can help me. Thanks.

**Comment by stellarhoof** [comment]
In my case, I'm implementing a Trello-like board. The sequence of events goes like:
- User initiates a drag event on a card
- Custom preview is rendered
- Card that initiated the drag is moved inside the container and hidden (to simulate unmounting, although real unmounting also triggers the exception)
- `HTML5Backend.prototype.handleTopDragStart` fails at https://github.com/react-dnd/react-dnd/blob/dbba380960d408014b8a6c4d7dfc508078a1a3f3/packages/react-dnd-html5-backend/src/HTML5Backend.ts#L407 because `sourceNode` is `undefined`, since the card has been moved.
