### ISSUE TITLE
Error appearing: Expected the backend to be a function or an ES6 module exporting a default function

### ISSUE THREAD

**Issue by alexandraclaire** [react-dnd/react-dnd#973]
I'm trying to set up react dnd, and I get this error every time, no matter what backend I use (html5, touch, multi) - any ideas on how to fix?

**Comment by drmason13** [comment]
@alexandraclaire I am experiencing the same issue. Have you had any luck since?
I have been following the tutorial but used create-react-app with [custom-react-scripts](https://www.npmjs.com/package/custom-react-scripts) to enable decorator syntax.

I first thought the error was with my decorator syntax but when I try to convert to es6 syntax I still get an error.

```
@DragDropContext(HTML5Backend)
export default class Board extends Component
```

```
class Board extends Component {
...
}
export default DragDropContext(HTML5Backend)(Board);
```
Both styles give the same error: `Expected the backend to be a function or an ES6 module exporting a default function. Read more: http://react-dnd.github.io/react-dnd/docs-drag-drop-context.html`

The content of the class doesn't matter:
```
class Board extends Component {
  render() {
    return <p>minimal test</p>;
  }
}
```

All I've done to get the backend is:
`import {HTML5Backend} from 'react-dnd-html5-backend';`

and it is installed, here's the package.json dependencies

```
  "dependencies": {
    "custom-react-scripts": "0.2.2",
    "react": "^16.3.1",
    "react-dnd": "^2.6.0",
    "react-dnd-html5-backend": "^2.6.0",
    "react-dom": "^16.3.1"
  },
```

digging further, npm list reports a LOT of missing dependencies - [gist](https://gist.github.com/drmason13/b45f1ec78716a5a5a2d9a321c85a2cc3). These are both caused by custom-react-scripts

Perhaps unsurprisingly uninstalling custom-react-scripts (which removed the npm errors) didn't affect the backend error. Still seeing `Expected the backend to be a function or an ES6 module exporting a default function. `

What else can I do to try and fix this?

**Comment by jwldnr** [comment]
you need to have your imports like this:

```
import HTML5Backend from "react-dnd-html5-backend"
import { DragDropContext } from "react-dnd"

...
```

note the _no brackets_ around the `HTML5Backend` import.

and your exports like this:

```
class App extends Component {
 /* code here */
}

export default DragDropContext(HTML5Backend)(App)
```

also make sure you're **not** doing this in your render function:

```
render() {
  return (
    <DragDropContext>
      ...
    </DragDropContext>
  )
)
```
