### ISSUE TITLE
Add support for React 16.3 createRef type of ref

### ISSUE THREAD

**Issue by janpe** [react-dnd/react-dnd#998]
Using connectDragSource with an element that is using the new createRef API (introduced in React 16.3.0) instead of callback refs causes the app to crash with the error: `TypeError: previousRef is not a function`.

https://github.com/facebook/react/pull/12162

**Comment by dantman** [comment]
Same issue. First time I finally get a chance to use the new refs and react-dnd is in the way.

Long term I'm not sure about the whole react-dnd model of using findDOMNode and replacing the ref. When React has new createRef and withRef. New [forwardRef API](https://reactjs.org/docs/forwarding-refs.html). And a number of APIs are starting to make use of render props.

But for now it should be sufficient to check if previousRef is an object with a `current` property and set that instead of calling it as a function.

**Comment by MattBubernak** [comment]
Anyone have any solutions for this, while still using createRef()?

**Comment by darthtrevino** [comment]
I can dig into this later, but a sandbox demonstrating what you're looking for would be great here.

**Comment by dhruvparmar372** [comment]
I'm facing the same issue as well. 
@darthtrevino https://codesandbox.io/s/733onvqwl6 maybe this sandbox helps.

**Comment by im-martijn** [comment]
Same issue. Should I revert to using the old callback ref, or is there a way to work around this?

**Comment by markvital** [comment]
+1
using `React.createRef()` and `ref.current` crashed the app.

When this will be fixed?

**Comment by AlexChrisF** [comment]
Still not fixed :/

**Comment by darthtrevino** [comment]
I'll make some time after react-conf to look into this

**Comment by arshmakker** [comment]
I was able to use a workaround as suggested by encapsulating the ref div inside another blank div.
example:
` <div>
        <div
          style={{
            position: "relative",
            borderStyle: "dashed",
            width: 300,
            height: 200,
            position: "relative"
          }}
          ref={this.myRef}
        />
      </div>`

**Comment by Edmondton** [comment]
👍 any update on this @darthtrevino.  would be great to hear an update

**Comment by piotrpawlik** [comment]
@darthtrevino Encountered same issue, could we get any ETA on the fix?

**Comment by darthtrevino** [comment]
should be today I think. Let me know if there are any issues with the release I cut later
